spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cast_avaliacao_prd
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    tomcat:
      max-active: 10
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        use_sql_comments: false
        format_sql: false
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect